### ISSUE TITLE
ROS randomly not starting at boot

### ISSUE THREAD

**Issue by mklomp** [mirte-robot/mirte-install-scripts#23]
Every now and then the systemd service mirte-ros does not start correctly because of a crash (see below) at boot. When starting it manually, it works. 

```
Oct 12 10:26:45 Mirte-3F6B81 bash[3058]: NODES
Oct 12 10:26:45 Mirte-3F6B81 bash[3058]:   /
Oct 12 10:26:45 Mirte-3F6B81 bash[3058]:     controller_spawner (controller_manager/spawner)
Oct 12 10:26:45 Mirte-3F6B81 bash[3058]:     mirte_base_node (mirte_control/mirte_control_node)
Oct 12 10:26:45 Mirte-3F6B81 bash[3058]:     mirte_telemetrix_mirte (mirte_telemetrix/ROS_telemetrix_aio_api.py)
Oct 12 10:26:45 Mirte-3F6B81 bash[3058]:     rosapi (rosapi/rosapi_node)
Oct 12 10:26:45 Mirte-3F6B81 bash[3058]:     rosbridge_websocket (rosbridge_server/rosbridge_websocket)
Oct 12 10:26:45 Mirte-3F6B81 bash[3058]:     web_video_server (web_video_server/web_video_server)
Oct 12 10:26:45 Mirte-3F6B81 bash[3058]:     webcam (usb_cam/usb_cam_node)
Oct 12 10:26:45 Mirte-3F6B81 bash[3058]: auto-starting new master
Oct 12 10:26:45 Mirte-3F6B81 bash[3058]: process[master]: started with pid [5011]
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]: Traceback (most recent call last):
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:   File "<frozen importlib._bootstrap_external>", line 1346, in _path_importer_cache
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]: KeyError: '/opt/ros/noetic/lib/python3/dist-packages/catkin'
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]: During handling of the above exception, another exception occurred:
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]: Traceback (most recent call last):
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:   File "/opt/ros/noetic/bin/rosmaster", line 35, in <module>
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:     rosmaster.rosmaster_main()
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:   File "/opt/ros/noetic/lib/python3/dist-packages/rosmaster/main.py", line 84, in rosmaster_main
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:     configure_logging()
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:   File "/opt/ros/noetic/lib/python3/dist-packages/rosmaster/main.py", line 58, in configure_logging
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:     _log_filename = rosgraph.roslogging.configure_logging('rosmaster', logging.DEBUG, filename=filename)
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:   File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/roslogging.py", line 192, in configure_logging
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:     logging.config.fileConfig(config_file, disable_existing_loggers=False)
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:   File "/usr/lib/python3.8/logging/config.py", line 79, in fileConfig
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:     handlers = _install_handlers(cp, formatters)
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:   File "/usr/lib/python3.8/logging/config.py", line 145, in _install_handlers
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:     h = klass(*args, **kwargs)
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:   File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/roslogging.py", line 237, in __init__
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:     from rospy.rostime import get_time, is_wallclock
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:   File "/opt/ros/noetic/lib/python3/dist-packages/rospy/__init__.py", line 49, in <module>
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:     from .client import spin, myargv, init_node, \
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:   File "/opt/ros/noetic/lib/python3/dist-packages/rospy/client.py", line 52, in <module>
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:     import roslib
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:   File "/opt/ros/noetic/lib/python3/dist-packages/roslib/__init__.py", line 53, in <module>
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:     import roslib.stacks  # noqa: F401, I100
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:   File "/opt/ros/noetic/lib/python3/dist-packages/roslib/stacks.py", line 45, in <module>
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:     import roslib.packages
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:   File "/opt/ros/noetic/lib/python3/dist-packages/roslib/packages.py", line 48, in <module>
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:     from catkin.find_in_workspaces import find_in_workspaces as catkin_find
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:   File "<frozen importlib._bootstrap>", line 914, in _find_spec
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:   File "<frozen importlib._bootstrap_external>", line 1407, in find_spec
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:   File "<frozen importlib._bootstrap_external>", line 1376, in _get_spec
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]:   File "<frozen importlib._bootstrap_external>", line 1348, in _path_importer_cache
Oct 12 10:26:45 Mirte-3F6B81 bash[5011]: KeyboardInterrupt
Oct 12 10:26:45 Mirte-3F6B81 bash[3058]: [master] killing on exit
Oct 12 10:26:46 Mirte-3F6B81 systemd[1]: mirte-ros.service: Main process exited, code=exited, status=1/FAILURE
Oct 12 10:26:46 Mirte-3F6B81 systemd[1]: mirte-ros.service: Failed with result 'exit-code'.
```

**Comment by ArendJan** [comment]
ros1, so closing
